// Placeholder IDL - Replace with actual IDL from your deployed program
// Copy the contents from target/idl/riddle_vault.json after running anchor build

export const IDL = {
  "version": "0.1.0",
  "name": "riddle_vault",
  "instructions": [
    {
      "name": "setWinner",
      "accounts": [
        {
          "name": "vault",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "authority",
          "isMut": false,
          "isSigner": true
        }
      ],
      "args": [
        {
          "name": "winner",
          "type": "publicKey"
        }
      ]
    },
    {
      "name": "claimPrize",
      "accounts": [
        {
          "name": "vault",
          "isMut": true,
          "isSigner": false
        },
        {
          "name": "claimer",
          "isMut": true,
          "isSigner": true
        }
      ],
      "args": []
    }
  ],
  "accounts": [
    {
      "name": "Vault",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "winner",
            "type": "publicKey"
          },
          {
            "name": "claimed",
            "type": "bool"
          }
        ]
      }
    }
  ]
};

// Note: This is a placeholder IDL. Replace with the actual IDL generated by anchor build
// The real IDL will be in target/idl/riddle_vault.json after you build your Solana program
